version: 0.1

phases:
  install:
    on-failure: ABORT
    commands:
      - ls
      - npm i

  build:
    on-failure: ABORT
    commands:
      - npm run build-static

artifacts:
  files:
    - out/*
  name: build-output